excerpt_separator: ""
pygments: true
markdown: kramdown
url: http://barrywise.github.io
name: Barry Wise
description: My awesome new site
author: Barry Wise
avatar: http://www.gravatar.com/avatar/d41d8cd98f00b204e9800998ecf8427e?s=120&d=mm&r=g
ga_domain: 
ga_tracking_id: 